log_file: "/path/to/log/file"
submission_file: "/path/to/submission/file"
stages:
  input:
    input:
      num_jobs: 1
      array_size: 0
      arguments: []
  prediagnostics:
    prediagnostics:
      num_jobs: 1
      array_size: 41
      arguments: ["reaches.json"]
  priors:
    priors:
      num_jobs: 1
      array_size: 6
      arguments: ["constrained", "grdc", "usgs", "gbpriors"]
  flpe:
    geobam:
      num_jobs: 1
      array_size: 41
      arguments: ["reaches.json"]
    hivdi:
      num_jobs: 1
      array_size: 41
      arguments: []
    metroman:
      num_jobs: 1
      array_size: 8
      arguments: ["sets.json"]
    momma:
      num_jobs: 1
      array_size: 41
      arguments: ["reaches.json"]
    sad:
      num_jobs: 1
      array_size: 41
      arguments: ["reaches.json"]
    sic4dvar:
      num_jobs: 1
      array_size: 41
      arguments: ["reaches.json"]
  postdiagnostics_flpe:
    postdiagnostics_flpe:
      num_jobs: 1
      array_size: 41
      arguments: []
  moi:
      moi:
        num_jobs: 1
        array_size: 5
        arguments: ["basin.json"]
  postdiagnostics_moi:
    postdiagnostics_moi:
      num_jobs: 1
      array_size: 41
      arguments: []
  offline:
    offline:
      num_jobs: 1
      array_size: 41
      arguments: []
  validation:
    validation:
      num_jobs: 1
      array_size: 0
      arguments: ["continent.json"]
  output:
    output:
      num_jobs: 1
      array_size: 6
      arguments: ["continent.json", "constrained"]