log_file: ""
submission_file: ""
stages:
  datagen:
    datagen:
      num_jobs: 1
      array_size: 0
      arguments: ["-c", "river", "-i", "3", "-d", "/data", "-o", "-k", "xxx"]
  combine_data:
    combine_data:
      num_jobs: 1
      array_size: 0
      arguments: ["-c","/data/continent.json","-d","/data"]
  input:
    input:
      num_jobs: 1
      array_size: 215
      arguments: ["-i", "-235", "-c", "river", "-r","/data/reach_node.json", "-p", "/data/cycle_passes.json", "-s", "/data/s3_list.json", "-d", "/data/swot"]
  priors:
    priors:
      num_jobs: 1
      array_size: 0
      arguments: ["-i", "3", "-r", "constrained", "-p", "usgs", "grdc", "riggs", "gbpriors"]