log_file: ""
submission_file: ""
stages:
  flpe:
    geobam:
      num_jobs: 1
      array_size: 10
      input_files: ["reaches.txt"]
    hivdi:
      num_jobs: 1
      array_size: 10
      input_files: ["reaches.txt"]
    metroman:
      num_jobs: 1
      array_size: 2
      input_files: ["reach_sets.txt"]
    momma:
      num_jobs: 1
      array_size: 10
      input_files: ["reaches.txt"]
    sad:
      num_jobs: 1
      array_size: 10
      input_files: ["reaches.txt"]