stages:
  input:
    input:
      num_jobs: 1
      array_size: 500
      input_files: []
  prediagnostics:
    prediagnostics:
      num_jobs: 1
      array_size: 500
      input_files: []
  flpe:
    geobam:
      num_jobs: 1
      array_size: 10
      input_files: ["reaches.txt"]
    hivdi:
      num_jobs: 1
      array_size: 10
      input_files: ["reaches.txt"]
    metroman:
      num_jobs: 1
      array_size: 10
      input_files: ["reaches.txt"]
    momma:
      num_jobs: 1
      array_size: 10
      input_files: ["reaches.txt"]
    sad:
      num_jobs: 1
      array_size: 10
      input_files: ["reaches.txt"]
  integrator:
      integrator:
        num_jobs: 1
        array_size: 500
        input_files: []
  consensus:
    consensus:
      num_jobs: 1
      array_size: 500
      input_files: []
  postdiagnostics:
    postdiagnostics:
      num_jobs: 1
      array_size: 500
      input_files: []
  validation:
    validation:
      num_jobs: 1
      array_size: 500
      input_files: []